GIFT:
  equaliseImageHistogram: true
  featureDist: 25.91373395034039
  featureSearchThreshold: 0.7
  maxError: 100.08998519259788
  maxFeatures: 40
  maxLevel: 3
  minHarrisQuality: 0.08859465154404257
  ransacParams:
    inlierThreshold: 0.000991045856248861
    maxIterations: 20
    minDataPoints: 10
    minInliers: 37
  trackedFeatureDist: 9.995503774595479
  winSize: 21
eqf:
  initialValue:
    sceneDepth: 8.891397050194614
  initialVariance:
    attitude: 0.10282752317467045
    biasAcc: 1.2232071190499316
    biasGyr: 1.1673134780260075
    cameraAttitude: 1.727825980507864e-07
    cameraPosition: 3.349654391578276e-07
    point: 100.0
    position: 0.00011220184543019634
    velocity: 3.6517412725483775e-06
  measurementNoise:
    feature: 3.7583740428844425
    featureOutlierAbs: 5.4509224619256385
    featureOutlierProb: 0.23374912831534894
    featureRetention: 0.2
  processVariance:
    attitude: 6.219421634147766e-08
    biasAcc: 0.0
    biasGyr: 0.0
    cameraAttitude: 2.2630153511576583e-06
    cameraPosition: 6.853895838650084e-07
    point: 0.000530103448340995
    position: 1.2589961848499808e-05
    velocity: 0.012232071190499315
  settings:
    coordinateChoice: InvDepth
    fastRiccati: true
    useDiscreteInnovationLift: false
    useDiscreteVelocityLift: true
    useEquivariantOutput: true
    useFeaturePredictions: false
    useInnovationLift: true
    useMedianDepth: false
  velocityNoise:
    acc: 3.262345818455677e-05
    accBias: 0.0063404671195099425
    gyr: 0.0011913242870580211
    gyrBias: 0.00020008996495836354
main:
  cameraLag: 0.012232071190499317
  limitRate: 0.0
  startTime: 0.0
  writeState: true
sim:
  cameraOffset:
  - xw
  - -0.04844625116694773
  - -0.08142350220051031
  - 0.003102425417307478
  - 0.7021240268103595
  - -0.006484783602096129
  - 0.013217864997878212
  - 0.7017528002920512
  fieldOfView: 60
  maxFeatures: 40
  numPoints: 5000
  randomSeed: 0
  wallDistance: 1.0